# Generated by Django 3.2.3 on 2022-11-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taxPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
