# Generated by Django 3.2.3 on 2022-11-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
