export const CART_ACTION_TYPES = {
    SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    SAVE_SHIPPING_ADDRESS:'SET_CART_SHIPPING_ADDRESS',
    SAVE_PAYMENT_METHOD:'SET_CART_PAYMENT_METHOD',
    CLEAR_CART_ITEMS:'CLEAR_CART_ITEMS',
  }